### ISSUE TITLE
Getting error on sign-in

### ISSUE THREAD

**Issue by abhayathapa** [davidwparker/programmingtil-rails#3]
NameError (uninitialized constant User::AllowlistedJwt):
app/models/concerns/users/allowlist.rb:21:in `on_jwt_dispatch'

**Comment by davidwparker** [comment]
@abhayathapa - what branch are you on?

**Comment by abhayathapa** [comment]
> @abhayathapa - what branch are you on?

@davidwparker  i was on main branch. Should i switch to other ?

**Comment by davidwparker** [comment]
The file is there on main. Can you check to make sure it's there in your files:
https://github.com/davidwparker/programmingtil-rails/blob/main/app/models/concerns/users/allowlist.rb
